language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: gusennan
  password:
    secure: P/FcXeNlTD/V07sSlXREcBDxO2fVK25aZzRBKqu+47o1MXwFSK35vFOLwgrnQAppdqLQob8PMbiKIJXl4uoVHvy3DyubyL2hDcOWFeKgpQ3AUkKbh8KRqVaQaPhID66fk7e5oSojq/xL+shej2ECXvRbNiY0R7fffu7P9kTQ4vGmMHu3ZewJ163uUdZkq7DWNztsW3R0MXaFgweBp1FxGYWIW1x+KKsj4ntAC1SEAR1N8HDSh0kFu3Aj8uc/10IoHiCZ+OsKER3s+Mc0051JcK5AYE45wbt9uZJWZ7uDFulx+XUfQQA0oSMpXkM4oflo3VV2Fjq+BNU1AmOnl4NTWm0i3XF1wXfsV6aOPULg47ySB8ojBjK0z2Wi3Lbaz0dVvucoJkPj00hq37VoB7U0uxnamBwaYNqQ4/+T5utccTmfzGRAjRswqpkZjlXfUFMO8jY4Bg9x+dHtYQYIR2liudAbZl2VCwkmC6Osj9sZO6c2/VPssDuJaOnyxfG4wkvlmCCJ3D1jjfzGRB33MJqoYEMZReQobHG5usRUxjxiYibMJBEQXeJ2y1qMkuatKd3cYiaGogVwhwgz0BB/9Wnl8OC2jYCkYYCG3ur3++DxFiZl3omp821lzEz0O6lByndSPZo/pkFGG1IyP6SLoJB6+yN2BqwciEeUYMIKxS9h9K8=
  on:
    tags: true
    repo: gusennan/polypeptideclient
    python: 3.8
